### ISSUE TITLE
Reporte 2_Ejercicios de hilos en consola

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-tec-design#1]
[TAP_U3_REPOR_2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-tec-design/files/15098902/TAP_U3_REPOR_2.pdf)

**Comment by Nancy-0714** [comment]
Calificación: 20
Si cumplen con los criterios de la rúbrica del reporte.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
